### ISSUE TITLE
elastic search version not showing

### ISSUE THREAD

**Issue by ceeram** [alt3/cakebox-console#75]
elastic search seems not to be running, perhaps needs fixing in alt3/cakebox?

**Comment by bravo-kernel** [comment]
Caused by a [flakey init script](https://gist.github.com/maxim/6032578) generated by the [elasticsearch cookbook](https://github.com/elastic/cookbook-elasticsearch) solved in their [pull 103](https://github.com/elastic/cookbook-elasticsearch/pull/103).

Will add a fix to the UpdateShell until we build a new box-image.

**Comment by bravo-kernel** [comment]
Fix does not work on 1GB boxes due to the [default ES_HEAP_SIZE of 1GB](http://www.elastic.co/guide/en/elasticsearch/reference/master/setup-configuration.html#_environment_variables).

Will be downsized to 256MB with instruction on how to increase.

**Comment by bravo-kernel** [comment]
It seems a more rigorous service restart was needed as well: https://github.com/alt3/cakebox-console/commit/cb35cfef12a6fda439fa5700ae7d8ed9226efc89

**Comment by bravo-kernel** [comment]
Closing as both Elasticsearch and Kibana have been tested successfully on a default 1GB cakebox.
